services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spoton_challenge
    ports:
      - "5432:5432"
    volumes:
      - spoton_challenge_pg:/var/lib/postgresql/data

volumes:
  spoton_challenge_pg:
